name: 'whatnot/ci'

on:
  push:
    branches-ignore:
      - main

jobs:
  terraform:
    name: test-terraform
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.2'

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        id: init
        run: terraform init -backend=false

      - name: Terraform validate
        id: validate
        run: terraform validate
